pub struct Beatmap {
    pub artist: String,
    pub artist_romanised: String,
    pub title: String,
    pub title_romanised: String,
    pub ar: f32,
    pub cs: f32,
    pub hp: f32,
    pub od: f32,
    pub audio_filename: String,
    pub background_filename: String,
    pub folder: String,
    pub creator: String,
    pub name: String,
    pub path: String,
    pub difficulty: String,
    pub map_id: i32,
    pub set_id: i32,
    pub ranked_status: i32,
    pub md5: String,
    pub object_count: i32,
    pub osu_file_name: String,
}
