[package]
name = "rosumemory-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read-process-memory = "0.1.6"
sysinfo = "0.29.0"
thiserror = "1.0.40"
whoami = "1.4.0"
